version: '3'

services:
  ghost-blog:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    restart: always
    depends_on:
      - "database"
    networks:
      - virtual-net-1
    environment:
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: ghostpass
      database__connection__database: ghost

  database:
    image: mysql:5.7
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - virtual-net-1
    environment:
      MYSQL_ROOT_PASSWORD: ghostpass

volumes:
  database_data:

networks:
  virtual-net-1: